# Generated by Django 5.1.7 on 2025-03-18 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="captcha",
        ),
    ]
